/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'squid' at '10/29/15 8:44 AM' with Gradle 2.8
 *
 * @author squid, @date 10/29/15 8:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
