import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'squid' at '10/29/15 8:51 AM' with Gradle 2.8
 *
 * @author squid, @date 10/29/15 8:51 AM
 */
public class DBTests {

}
