/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'squid' at '10/29/15 8:43 AM' with Gradle 2.8
 *
 * @author squid, @date 10/29/15 8:43 AM
 */
public class AresApiTests {

}
